#!/usr/bin/env python3
"""
Quality Gate — the anti-slop system every deliverable must pass through.

Run BEFORE any deliverable is submitted to ACP. Checks:
1. Requirement coverage — does the deliverable address every requirement?
2. Slop detection — banned AI phrases + structural patterns
3. Evidence quality — file refs, quantitative data, source citations

Pass threshold: score >= 85/100
"""

from pathlib import Path
import re
from datetime import datetime

BANNED_PHRASES = [
    r"as an ai",
    r"i cannot browse",
    r"as an ai language model",
    r"in today's digital age",
    r"in today's (?:fast[-\s]?paced|ever[-\s]?evolving|dynamic landscape)",
    r"it is important to note",
    r"it's worth noting that",
    r"please note that",
    r"kindly note",
    r"ai-generated",
    r"generated by ai",
    r"lorem ipsum",
    r"placeholder",
    r"insert here",
    r"example\.com",
    r"todo",
    r"fixme",
]

BANNED_COMPILED = [re.compile(p, re.IGNORECASE) for p in BANNED_PHRASES]


# Structural slop detectors
def check_rule_of_three(text: str) -> bool:
    """Detect 3+ consecutive short bullet items."""
    lines = text.split("\n")
    triple = 0
    for line in lines:
        if re.match(r"^[-*]\s", line) and len(line.strip()) < 60:
            triple += 1
            if triple >= 3:
                return True
        else:
            triple = 0
    return False


def check_uniform_sentence_length(text: str) -> bool:
    """Detect 3+ consecutive sentences of similar length."""
    sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
    if len(sentences) < 3:
        return False
    matches = 0
    for i in range(len(sentences) - 2):
        l1, l2, l3 = len(sentences[i]), len(sentences[i+1]), len(sentences[i+2])
        if abs(l1-l2) <= 3 and abs(l2-l3) <= 3:
            matches += 1
            if matches >= 3:
                return True
    return False


def check_listicle_opener(text: str) -> bool:
    """Detect AI listicle openers."""
    return bool(re.search(
        r"\b(in this|this (?:article|guide|post)|today we'll|let's explore)",
        text, re.IGNORECASE
    ))


STRUCTURAL_PATTERNS = [
    ("Rule of Three", check_rule_of_three),
    ("Uniform sentence length", check_uniform_sentence_length),
    ("AI listicle opener", check_listicle_opener),
]


class QualityGate:
    """Anti-slop quality checker for AI-generated deliverables."""

    PASS_THRESHOLD = 85

    def check(self, job: dict, result: dict) -> dict:
        """
        Check a deliverable against all quality criteria.
        Returns {passed, score, issues, evidence}.
        """
        issues: list[str] = []
        evidence: list[str] = []

        # --- Requirement coverage (40%) ---
        requirements = self._extract_requirements(job, result)
        coverage_score = self._check_coverage(result, requirements, issues, evidence)

        # --- Slop detection (35%) ---
        slop_score = self._check_slop(result.get("deliverable", ""), issues, evidence)

        # --- Evidence quality (25%) ---
        evidence_score = self._check_evidence(result.get("evidence", []), issues, evidence)

        # --- Final score ---
        score = round(coverage_score * 0.40 + slop_score * 0.35 + evidence_score * 0.25)
        passed = score >= self.PASS_THRESHOLD

        if not passed:
            issues.append(f"Overall quality score: {score}/100 (threshold: {self.PASS_THRESHOLD})")

        return {
            "passed": passed,
            "score": score,
            "issues": issues,
            "evidence": evidence,
            "requirement_coverage": coverage_score,
            "slop_score": slop_score,
            "evidence_score": evidence_score,
        }

    def _extract_requirements(self, job: dict, result: dict) -> list[str]:
        """Extract explicit requirements from the job description."""
        reqs = []
        desc = job.get("description", "") or job.get("name", "")

        patterns = [
            r"must\s+(?:include|have|provide|produce)[\s\S]*?(?=\n\n|\Z)",
            r"should\s+(?:include|have|provide|produce)[\s\S]*?(?=\n\n|\Z)",
            r"requirement[s]?:\s*(.+)",
        ]

        for pattern in patterns:
            match = re.search(pattern, desc, re.IGNORECASE)
            if match:
                reqs.append(match.group(0).strip())

        return reqs

    def _check_coverage(self, result: dict, requirements: list[str],
                        issues: list[str], evidence: list[str]) -> int:
        """Check that all requirements are addressed."""
        if not requirements:
            return 100

        text = (result.get("deliverable", "") + " " +
                " ".join(result.get("evidence", []))).lower()

        missing = []
        for req in requirements:
            keywords = re.sub(r"(must|should|requirement[s]?|include|have|provide)",
                            "", req.lower())
            keywords = [kw for kw in keywords.split() if len(kw) > 3]
            if not any(kw in text for kw in keywords):
                missing.append(req)

        score = 100 - (len(missing) / len(requirements)) * 100
        for m in missing:
            issues.append(f"Unmet requirement: {m}")

        return round(score)

    def _check_slop(self, text: str, issues: list[str], evidence: list[str]) -> int:
        """AI-slop detection — banned phrases + structural patterns."""
        score = 100
        slop_count = 0

        # Phrase-level
        seen = set()
        for i, regex in enumerate(BANNED_COMPILED):
            matches = regex.findall(text)
            if matches:
                slop_count += len(matches)
                label = BANNED_PHRASES[i]
                if label not in seen:
                    issues.append(f"Banned phrase \"{label}\" found {len(matches)} time(s)")
                    seen.add(label)

        # Structural
        for name, detector in STRUCTURAL_PATTERNS:
            if detector(text):
                slop_count += 1
                issues.append(f"Structural slop detected: {name}")

        score = max(0, 100 - slop_count * 5)
        evidence.append(f"Slop scan: {slop_count} violations, score {score}/100")
        return score

    def _check_evidence(self, evidence_list: list[str], issues: list[str],
                        evidence: list[str]) -> int:
        """Evidence quality check."""
        if not evidence_list:
            issues.append("No evidence artifacts provided")
            return 0

        score = 100

        # File path references
        file_paths = [e for e in evidence_list if any(c in e for c in "/\\") and
                       any(e.endswith(ext) for ext in [".md", ".json", ".sarif", ".js", ".ts", ".py"])]
        if not file_paths:
            issues.append("Evidence has no file path references")
            score -= 15

        # Quantitative data
        data_refs = [e for e in evidence_list if re.search(r"\d+", e)]
        if not data_refs:
            issues.append("Evidence lacks quantitative data")
            score -= 15

        # Source citations / artifact refs
        citations = [e for e in evidence_list if any(
            kw in e.lower() for kw in ["source:", "src:", "url:", "file:", "artifacts/", ".md", ".json", ".sarif"])]
        if not citations:
            issues.append("Evidence lacks source citations or artifact refs")
            score -= 10

        evidence.append(f"Evidence quality: {len(file_paths)} file refs, "
                        f"{len(data_refs)} data refs, {len(citations)} citations")
        return max(0, score)
